/* =====================================================================
   EMBERGRAVE — data overrides (auto-generated by editor.html)
   Patches item & monster data on top of the pristine data.js. Edit via the
   GUI tool (editor.html), not by hand. Delete the body below to revert.
   ===================================================================== */
if (typeof DATA !== "undefined" && DATA.applyOverrides) DATA.applyOverrides(
{
}
);
