/* Recorded skill audio identities; generated by tools/create_skill_audio_catalog.py. */
'use strict';
const SkillAudioCatalog = (() => {
  const families = {"steel":["cloth","blade","steel","cloth",null],"fire":["cloth","ember","fire","ember","fire"],"frost":["cloth","ice","frost","ice","wind"],"storm":["cloth","spark","spark","wind","wind"],"bone":["bone","bone","bone","bone",null],"hex":["shadow","hex","hex","breath","hex"],"poison":["cloth","rot","rot","rot","wind"],"shadow":["cloth","shadow","blood","shadow","wind"],"earth":["roots","stone","stone","stone","wind"],"blood":["cloth","blade","blood","breath",null],"nature":["roots","growl","blood","roots",null],"bow":["draw","bow","arrow","cloth","draw"],"trap":["latch","latch","steel","latch",null],"warcry":["breath","howl","shield","breath",null],"banner":["cloth","chain","shield","cloth",null],"shield":["cloth","shield","shield","chain",null],"chain":["chain","chain","steel","chain",null]};
  const recipes = {
  "vanguard_0_0": {
    "family": "steel",
    "motif": "slash",
    "weight": 1,
    "rate": 0.95,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "vanguard_0_1": {
    "family": "steel",
    "motif": "finish",
    "weight": 1.25,
    "rate": 0.965,
    "accent": "shield",
    "passive": false,
    "trigger": null
  },
  "vanguard_0_2": {
    "family": "shield",
    "motif": "parry",
    "weight": 1,
    "rate": 0.98,
    "accent": "chain",
    "passive": false,
    "trigger": null
  },
  "vanguard_0_3": {
    "family": "steel",
    "motif": "passive:weapon",
    "weight": 0.82,
    "rate": 0.995,
    "accent": null,
    "passive": true,
    "trigger": null
  },
  "vanguard_0_4": {
    "family": "blood",
    "motif": "stance",
    "weight": 1,
    "rate": 1.01,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "vanguard_0_5": {
    "family": "shield",
    "motif": "bulwark",
    "weight": 1,
    "rate": 1.025,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "vanguard_0_6": {
    "family": "blood",
    "motif": "execute",
    "weight": 1.25,
    "rate": 1.04,
    "accent": "blood",
    "passive": false,
    "trigger": null
  },
  "vanguard_1_0": {
    "family": "warcry",
    "motif": "shout",
    "weight": 1,
    "rate": 0.95,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "terrifying_bellow": {
    "family": "warcry",
    "motif": "fear",
    "weight": 1,
    "rate": 0.965,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "vanguard_1_2": {
    "family": "banner",
    "motif": "banner",
    "weight": 1,
    "rate": 0.98,
    "accent": "cloth",
    "passive": false,
    "trigger": null
  },
  "vanguard_1_3": {
    "family": "steel",
    "motif": "passive:defense",
    "weight": 0.82,
    "rate": 0.995,
    "accent": null,
    "passive": true,
    "trigger": null
  },
  "vanguard_1_4": {
    "family": "warcry",
    "motif": "roar",
    "weight": 1.25,
    "rate": 1.01,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "vanguard_1_5": {
    "family": "banner",
    "motif": "standard",
    "weight": 1,
    "rate": 1.025,
    "accent": "cloth",
    "passive": false,
    "trigger": null
  },
  "vanguard_2_0": {
    "family": "earth",
    "motif": "charge",
    "weight": 1,
    "rate": 1.04,
    "accent": "cloth",
    "passive": false,
    "trigger": null
  },
  "vanguard_2_1": {
    "family": "chain",
    "motif": "grapple",
    "weight": 1,
    "rate": 0.95,
    "accent": "latch",
    "passive": false,
    "trigger": null
  },
  "vanguard_2_2": {
    "family": "steel",
    "motif": "axe",
    "weight": 1,
    "rate": 0.965,
    "accent": "steel",
    "passive": false,
    "trigger": null
  },
  "vanguard_2_3": {
    "family": "earth",
    "motif": "passive:movement",
    "weight": 0.82,
    "rate": 0.98,
    "accent": null,
    "passive": true,
    "trigger": null
  },
  "ground_slam": {
    "family": "earth",
    "motif": "fissure",
    "weight": 1.25,
    "rate": 0.995,
    "accent": "roots",
    "passive": false,
    "trigger": null
  },
  "vanguard_2_5": {
    "family": "shield",
    "motif": "bash",
    "weight": 1,
    "rate": 1.01,
    "accent": "chain",
    "passive": false,
    "trigger": null
  },
  "vanguard_2_6": {
    "family": "earth",
    "motif": "leap",
    "weight": 1.25,
    "rate": 1.025,
    "accent": "roots",
    "passive": false,
    "trigger": null
  },
  "emberwitch_0_0": {
    "family": "fire",
    "motif": "ember",
    "weight": 1,
    "rate": 1.04,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "emberwitch_0_1": {
    "family": "fire",
    "motif": "cinders",
    "weight": 1,
    "rate": 0.95,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "emberwitch_0_2": {
    "family": "fire",
    "motif": "passive:fire",
    "weight": 0.82,
    "rate": 0.965,
    "accent": null,
    "passive": true,
    "trigger": "fire"
  },
  "emberwitch_0_3": {
    "family": "fire",
    "motif": "wall",
    "weight": 1,
    "rate": 0.98,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "emberwitch_0_4": {
    "family": "fire",
    "motif": "meteor",
    "weight": 1.25,
    "rate": 0.995,
    "accent": "thunder",
    "passive": false,
    "trigger": null
  },
  "emberwitch_0_5": {
    "family": "fire",
    "motif": "pyre",
    "weight": 1,
    "rate": 1.01,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "emberwitch_0_6": {
    "family": "fire",
    "motif": "inferno",
    "weight": 1.25,
    "rate": 1.025,
    "accent": "thunder",
    "passive": false,
    "trigger": null
  },
  "emberwitch_1_0": {
    "family": "frost",
    "motif": "shard",
    "weight": 1,
    "rate": 1.04,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "emberwitch_1_1": {
    "family": "frost",
    "motif": "nova",
    "weight": 1,
    "rate": 0.95,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "emberwitch_1_2": {
    "family": "frost",
    "motif": "passive:frozen",
    "weight": 0.82,
    "rate": 0.965,
    "accent": null,
    "passive": true,
    "trigger": "frozen"
  },
  "emberwitch_1_3": {
    "family": "frost",
    "motif": "lance",
    "weight": 1,
    "rate": 0.98,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "emberwitch_1_4": {
    "family": "frost",
    "motif": "frostchain",
    "weight": 1,
    "rate": 0.995,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "rimeguard": {
    "family": "frost",
    "motif": "rimeward",
    "weight": 1,
    "rate": 1.01,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "emberwitch_1_6": {
    "family": "frost",
    "motif": "glacier",
    "weight": 1.25,
    "rate": 1.025,
    "accent": "stone",
    "passive": false,
    "trigger": null
  },
  "spark": {
    "family": "storm",
    "motif": "sparks",
    "weight": 1,
    "rate": 1.04,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "stormshell": {
    "family": "storm",
    "motif": "stormward",
    "weight": 1,
    "rate": 0.95,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "emberwitch_2_2": {
    "family": "storm",
    "motif": "lightning",
    "weight": 1,
    "rate": 0.965,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "emberwitch_2_3": {
    "family": "storm",
    "motif": "orb",
    "weight": 1,
    "rate": 0.98,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "emberwitch_2_4": {
    "family": "storm",
    "motif": "arcblink",
    "weight": 1,
    "rate": 0.995,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "emberwitch_2_5": {
    "family": "storm",
    "motif": "static",
    "weight": 1,
    "rate": 1.01,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "emberwitch_2_6": {
    "family": "storm",
    "motif": "overload",
    "weight": 1.25,
    "rate": 1.025,
    "accent": "thunder",
    "passive": false,
    "trigger": null
  },
  "raise_dead": {
    "family": "bone",
    "motif": "skeleton",
    "weight": 1,
    "rate": 1.04,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "raise_plaguemage": {
    "family": "poison",
    "motif": "mage",
    "weight": 1,
    "rate": 0.95,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "gravebinder_0_2": {
    "family": "bone",
    "motif": "golem",
    "weight": 1.25,
    "rate": 0.965,
    "accent": "stone",
    "passive": false,
    "trigger": null
  },
  "gravebinder_0_3": {
    "family": "bone",
    "motif": "passive:minion",
    "weight": 0.82,
    "rate": 0.98,
    "accent": null,
    "passive": true,
    "trigger": "minion"
  },
  "gravebinder_0_4": {
    "family": "bone",
    "motif": "bonearmor",
    "weight": 1,
    "rate": 0.995,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "gravebinder_0_5": {
    "family": "bone",
    "motif": "bonespear",
    "weight": 1,
    "rate": 1.01,
    "accent": "blade",
    "passive": false,
    "trigger": null
  },
  "dread_muster": {
    "family": "warcry",
    "motif": "muster",
    "weight": 1.25,
    "rate": 1.025,
    "accent": "bone",
    "passive": false,
    "trigger": null
  },
  "gravebinder_0_7": {
    "family": "fire",
    "motif": "sacrifice",
    "weight": 1.25,
    "rate": 1.04,
    "accent": "blood",
    "passive": false,
    "trigger": null
  },
  "mark_of_frailty": {
    "family": "hex",
    "motif": "frailty",
    "weight": 1,
    "rate": 0.95,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "withering_hex": {
    "family": "poison",
    "motif": "wither",
    "weight": 1,
    "rate": 0.965,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "gravebinder_1_2": {
    "family": "hex",
    "motif": "doom",
    "weight": 1,
    "rate": 0.98,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "gravebinder_1_3": {
    "family": "hex",
    "motif": "beckon",
    "weight": 1,
    "rate": 0.995,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "gravebinder_1_4": {
    "family": "hex",
    "motif": "passive:curse",
    "weight": 0.82,
    "rate": 1.01,
    "accent": null,
    "passive": true,
    "trigger": "curse"
  },
  "gravebinder_1_5": {
    "family": "hex",
    "motif": "siphon",
    "weight": 1,
    "rate": 1.025,
    "accent": "breath",
    "passive": false,
    "trigger": null
  },
  "gravebinder_1_6": {
    "family": "hex",
    "motif": "passive:kill",
    "weight": 0.82,
    "rate": 1.04,
    "accent": null,
    "passive": true,
    "trigger": "kill"
  },
  "gravebinder_1_7": {
    "family": "hex",
    "motif": "reap",
    "weight": 1,
    "rate": 0.95,
    "accent": "blade",
    "passive": false,
    "trigger": null
  },
  "venom_spit": {
    "family": "poison",
    "motif": "venom",
    "weight": 1,
    "rate": 0.965,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "gravebinder_2_1": {
    "family": "poison",
    "motif": "seed",
    "weight": 1,
    "rate": 0.98,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "gravebinder_2_2": {
    "family": "poison",
    "motif": "miasma",
    "weight": 1,
    "rate": 0.995,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "gravebinder_2_3": {
    "family": "poison",
    "motif": "passive:corpse",
    "weight": 0.82,
    "rate": 1.01,
    "accent": null,
    "passive": true,
    "trigger": null
  },
  "gravebinder_2_4": {
    "family": "bone",
    "motif": "devour",
    "weight": 1,
    "rate": 1.025,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "corpse_burst": {
    "family": "poison",
    "motif": "corpse",
    "weight": 1.25,
    "rate": 1.04,
    "accent": "bone",
    "passive": false,
    "trigger": null
  },
  "gravebinder_2_6": {
    "family": "bone",
    "motif": "cadaver",
    "weight": 1,
    "rate": 0.95,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "gravebinder_2_7": {
    "family": "poison",
    "motif": "outbreak",
    "weight": 1.25,
    "rate": 0.965,
    "accent": "breath",
    "passive": false,
    "trigger": null
  },
  "veilranger_0_0": {
    "family": "bow",
    "motif": "arrow",
    "weight": 1,
    "rate": 0.98,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "veilranger_0_1": {
    "family": "bow",
    "motif": "volley",
    "weight": 1,
    "rate": 0.995,
    "accent": "cloth",
    "passive": false,
    "trigger": null
  },
  "veilranger_0_2": {
    "family": "bow",
    "motif": "draw",
    "weight": 1,
    "rate": 1.01,
    "accent": "draw",
    "passive": false,
    "trigger": null
  },
  "veilranger_0_3": {
    "family": "steel",
    "motif": "passive:weapon",
    "weight": 0.82,
    "rate": 1.025,
    "accent": null,
    "passive": true,
    "trigger": null
  },
  "veilranger_0_4": {
    "family": "bow",
    "motif": "ricochet",
    "weight": 1,
    "rate": 1.04,
    "accent": "steel",
    "passive": false,
    "trigger": null
  },
  "veilranger_0_5": {
    "family": "bow",
    "motif": "skewer",
    "weight": 1,
    "rate": 0.95,
    "accent": "blade",
    "passive": false,
    "trigger": null
  },
  "veilranger_0_6": {
    "family": "bow",
    "motif": "rain",
    "weight": 1.25,
    "rate": 0.965,
    "accent": "wind",
    "passive": false,
    "trigger": null
  },
  "veilranger_1_0": {
    "family": "trap",
    "motif": "barbed",
    "weight": 1,
    "rate": 0.98,
    "accent": "chain",
    "passive": false,
    "trigger": null
  },
  "veilranger_1_1": {
    "family": "steel",
    "motif": "passive:trap",
    "weight": 0.82,
    "rate": 0.995,
    "accent": null,
    "passive": true,
    "trigger": null
  },
  "veilranger_1_2": {
    "family": "frost",
    "motif": "frosttrap",
    "weight": 1,
    "rate": 1.01,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "veilranger_1_3": {
    "family": "trap",
    "motif": "tripwire",
    "weight": 1,
    "rate": 1.025,
    "accent": "latch",
    "passive": false,
    "trigger": null
  },
  "veilranger_1_4": {
    "family": "trap",
    "motif": "caltrop",
    "weight": 1,
    "rate": 1.04,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "veilranger_1_5": {
    "family": "fire",
    "motif": "powder",
    "weight": 1.25,
    "rate": 0.95,
    "accent": "stone",
    "passive": false,
    "trigger": null
  },
  "veilranger_1_6": {
    "family": "shadow",
    "motif": "decoy",
    "weight": 1,
    "rate": 0.965,
    "accent": "cloth",
    "passive": false,
    "trigger": null
  },
  "veilranger_2_0": {
    "family": "shadow",
    "motif": "blink",
    "weight": 1,
    "rate": 0.98,
    "accent": "breath",
    "passive": false,
    "trigger": null
  },
  "veilranger_2_1": {
    "family": "shadow",
    "motif": "smoke",
    "weight": 1,
    "rate": 0.995,
    "accent": "wind",
    "passive": false,
    "trigger": null
  },
  "veilranger_2_2": {
    "family": "shadow",
    "motif": "passive:movement",
    "weight": 0.82,
    "rate": 1.01,
    "accent": null,
    "passive": true,
    "trigger": null
  },
  "veilranger_2_3": {
    "family": "blood",
    "motif": "coat",
    "weight": 1,
    "rate": 1.025,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "veilranger_2_4": {
    "family": "blood",
    "motif": "mark",
    "weight": 1,
    "rate": 1.04,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "veilranger_2_5": {
    "family": "shadow",
    "motif": "afterimage",
    "weight": 1,
    "rate": 0.95,
    "accent": "blade",
    "passive": false,
    "trigger": null
  },
  "veilranger_2_6": {
    "family": "blood",
    "motif": "hemorrhage",
    "weight": 1.25,
    "rate": 0.965,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "call_wolf": {
    "family": "nature",
    "motif": "wolf",
    "weight": 1,
    "rate": 0.98,
    "accent": "roots",
    "passive": false,
    "trigger": null
  },
  "thornback_boar": {
    "family": "earth",
    "motif": "boar",
    "weight": 1,
    "rate": 0.995,
    "accent": "growl",
    "passive": false,
    "trigger": null
  },
  "wildkeeper_0_2": {
    "family": "storm",
    "motif": "hawk",
    "weight": 1,
    "rate": 1.01,
    "accent": "wind",
    "passive": false,
    "trigger": null
  },
  "wildkeeper_0_3": {
    "family": "nature",
    "motif": "bear",
    "weight": 1.25,
    "rate": 1.025,
    "accent": "roots",
    "passive": false,
    "trigger": null
  },
  "kinship": {
    "family": "nature",
    "motif": "passive:minion",
    "weight": 0.82,
    "rate": 1.04,
    "accent": null,
    "passive": true,
    "trigger": "minion"
  },
  "feral_howl": {
    "family": "warcry",
    "motif": "howl",
    "weight": 1,
    "rate": 0.95,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "wildkeeper_0_6": {
    "family": "blood",
    "motif": "packsacrifice",
    "weight": 1,
    "rate": 0.965,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "wildkeeper_1_0": {
    "family": "storm",
    "motif": "totem",
    "weight": 1,
    "rate": 0.98,
    "accent": "roots",
    "passive": false,
    "trigger": null
  },
  "totem_mastery": {
    "family": "storm",
    "motif": "passive:totem",
    "weight": 0.82,
    "rate": 0.995,
    "accent": null,
    "passive": true,
    "trigger": null
  },
  "ground_fissure": {
    "family": "earth",
    "motif": "fissure",
    "weight": 1.25,
    "rate": 1.01,
    "accent": "roots",
    "passive": false,
    "trigger": null
  },
  "wildkeeper_1_3": {
    "family": "storm",
    "motif": "cyclone",
    "weight": 1,
    "rate": 1.025,
    "accent": "wind",
    "passive": false,
    "trigger": null
  },
  "wildkeeper_1_4": {
    "family": "nature",
    "motif": "passive:totem",
    "weight": 0.82,
    "rate": 1.04,
    "accent": null,
    "passive": true,
    "trigger": null
  },
  "wildkeeper_1_5": {
    "family": "earth",
    "motif": "quake",
    "weight": 1.25,
    "rate": 0.95,
    "accent": "roots",
    "passive": false,
    "trigger": null
  },
  "wildkeeper_1_6": {
    "family": "storm",
    "motif": "tempest",
    "weight": 1.25,
    "rate": 0.965,
    "accent": "thunder",
    "passive": false,
    "trigger": null
  },
  "fangform": {
    "family": "nature",
    "motif": "fangform",
    "weight": 1,
    "rate": 0.98,
    "accent": "roots",
    "passive": false,
    "trigger": null
  },
  "stoneform": {
    "family": "nature",
    "motif": "bearform",
    "weight": 1,
    "rate": 0.995,
    "accent": "roots",
    "passive": false,
    "trigger": null
  },
  "wildkeeper_2_2": {
    "family": "earth",
    "motif": "stoneform",
    "weight": 1.25,
    "rate": 1.01,
    "accent": "roots",
    "passive": false,
    "trigger": null
  },
  "primal_surge": {
    "family": "fire",
    "motif": "passive:primal",
    "weight": 0.82,
    "rate": 1.025,
    "accent": null,
    "passive": true,
    "trigger": "primal"
  },
  "rabies": {
    "family": "poison",
    "motif": "rabies",
    "weight": 1,
    "rate": 1.04,
    "accent": null,
    "passive": false,
    "trigger": null
  },
  "fire_claw": {
    "family": "fire",
    "motif": "claw",
    "weight": 1,
    "rate": 0.95,
    "accent": "blade",
    "passive": false,
    "trigger": null
  },
  "wildkeeper_2_6": {
    "family": "fire",
    "motif": "apexform",
    "weight": 1.25,
    "rate": 0.965,
    "accent": "growl",
    "passive": false,
    "trigger": null
  },
  "basic": {
    "family": "steel",
    "motif": "slash",
    "weight": 0.86,
    "rate": 1,
    "accent": null,
    "passive": false,
    "trigger": null
  }
};
  for(const row of Object.values(recipes))Object.freeze(row);
  for(const row of Object.values(families))Object.freeze(row);
  return Object.freeze({recipes:Object.freeze(recipes),families:Object.freeze(families)});
})();
