import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {webcrypto} from 'node:crypto';
import {fixture} from './boss_fixture.mjs';
const f=fixture(),{ctx,Game:G,Items:I,MapGen:M}=f;
Object.assign(ctx,{crypto:webcrypto,structuredClone,Float64Array});
Object.assign(ctx.Player3D.assets,{resolvePlayerVisual:classId=>({kind:'player3d',classId}),loadPlayerLoadout:async()=>{}});
ctx.Coop={active:true,host:true,authority:true,committing:true,loading:false,save(){},event(){}};
for(const file of ['management','coop_protocol','coop_codec','coop_commands'])vm.runInContext(fs.readFileSync(new URL('../js/'+file+'.js',import.meta.url),'utf8'),ctx);
const {CoopCodec:C,CoopCommands:Cmd}=vm.runInContext('({CoopCodec,CoopCommands})',ctx);
const {s,p,m:boss}=f.fresh('korvath');
const bossSnapshot=C.snapshot({...s,players:[p]},1,1,true);
assert.equal(bossSnapshot.groups.monsters.find(m=>m._coopId===boss._coopId).encounter.statusLabel,boss.encounter.statusText());s.map=M.generate('frosthaven',321);s.monsters=[];p.heroId='inventory_hero';p._coopId='host';s.players=[p];
p.inv=I.makeGrid(10,4);p.equip={};p.stash=I.makeGrid(10,6);p.gold=200;
s.map.props.push({interact:'storage',x:p.x,y:p.y,surfaceId:p.surfaceId},{interact:'forge',x:p.x,y:p.y,surfaceId:p.surfaceId});
let checks=0;const ok=(v,m)=>{assert.ok(v,m);checks++;};
const add=it=>{assert.ok(I.autoPlace(p.inv,it));C.register(s);return it;};
const cmd=c=>Cmd.execute(p,c);
const potion=add(I.makeConsumable('hp1',3)),other=add(I.makeConsumable('mp1',2));
await cmd({type:'carry',itemId:potion._coopId});
ok(!p.inv.items.includes(potion)&&p.management.carried===potion,'carrying has exactly one owner and frees the source cells');
await cmd({type:'place',itemId:potion._coopId,to:'inv',x:other.gx,y:other.gy,targetId:other._coopId});
ok(p.management.carried===other&&p.inv.items.includes(potion),'placement swaps one overlapping item onto the cursor');
await cmd({type:'place',itemId:other._coopId,to:'stash',x:8,y:5,targetId:null});
ok(other.gx===8&&other.gy===5&&!p.management.carried,'carried item places at exact stash coordinates');
await cmd({type:'carry',itemId:other._coopId});
await cmd({type:'returnManagement'});
ok(p.stash.items.includes(other)&&other.gx===8&&other.gy===5,'closing restores the original stash location');
const restored=C.restoreHero(C.hero(p));
ok(restored.stash.items[0].gx===8&&restored.stash.items[0].gy===5,'saved grid coordinates survive reload');
const second=add(I.makeConsumable('hp1',9));
// autoPlace may merge stacks; create a separate stack deliberately for the carry interaction.
const stack=I.makeConsumable('hp1',7);I.place(p.inv,stack,8,3);C.register(s);
const target=p.inv.items.find(it=>it.baseId==='hp1'&&it!==stack);target.count=8;
await cmd({type:'carry',itemId:stack._coopId});
await cmd({type:'place',itemId:stack._coopId,to:'inv',x:target.gx,y:target.gy,targetId:target._coopId});
ok(target.count===10&&p.management.carried.count===5,'partial stack merge preserves the carried remainder');
const before=JSON.stringify(p.inv);
await assert.rejects(()=>cmd({type:'place',itemId:stack._coopId,to:'inv',x:-1,y:0,targetId:null}));checks++;
ok(JSON.stringify(p.inv)===before&&p.management.carried===stack,'invalid placement leaves both owners unchanged');
await assert.rejects(()=>cmd({type:'place',itemId:'foreign_item',to:'inv',x:0,y:0}));checks++;
const heldSave=C.hero(p),heldRound=C.restoreHero(heldSave);
ok(heldRound.management.carried._coopId===stack._coopId&&!heldRound.inv.items.some(it=>it._coopId===stack._coopId),'carried item survives save without duplication');
const snapshot=C.snapshot(s,1,1,true),copy={...s,players:[],monsters:[],minions:[],projectiles:[],traps:[],fx:[],npcs:[],ground:[],map:{...s.map,props:[]}};
C.apply(copy,JSON.parse(JSON.stringify(snapshot)),'host');
ok(copy.player.management.carried.count===5,'snapshot includes carried item data, not an unresolved reference');
await cmd({type:'cancelCarry'});
const sword=add(I.fromBase('shortsword'));sword.identified=true;
await cmd({type:'equip',itemId:sword._coopId});
await cmd({type:'carry',itemId:sword._coopId});
ok(!p.equip.main&&p.management.carried===sword,'equipment can be lifted onto the shared cursor');
await cmd({type:'cancelCarry'});ok(p.equip.main===sword,'cancel restores compatible original equipment');
await cmd({type:'unequip',slot:'main',itemId:sword._coopId});ok(p.inv.items.includes(sword),'right-click unequip goes to pack');
const glyphKey=Object.keys(vm.runInContext('DATA.GLYPHS',ctx))[0],offering=[];
for(let i=0;i<3;i++){
  const it=add(I.makeGlyph(glyphKey));offering.push(it._coopId);
  await cmd({type:'carry',itemId:it._coopId});await cmd({type:'offer',slot:i,itemId:it._coopId,expectedId:null});
}
ok(p.management.offer.filter(Boolean).length===3&&offering.every(id=>!p.inv.items.some(it=>it._coopId===id)),'offering slots have exclusive host ownership');
const forgedSave=C.hero(p);ok(C.restoreHero(forgedSave).management.offer.filter(Boolean).length===3,'forge offerings survive reload');
await assert.rejects(()=>cmd({type:'offer',slot:0,itemId:null,expectedId:'stale'}));checks++;
await cmd({type:'craft',recipe:'glyph',items:offering});
ok(p.management.offer.every(it=>!it)&&offering.every(id=>!p.inv.items.some(it=>it._coopId===id)),'craft consumes each offering once');
await assert.rejects(()=>cmd({type:'craft',recipe:'glyph',items:offering}));checks++;
const old=C.hero(p);delete old.management;ok(!C.restoreHero(old).management.carried,'legacy saves default to empty management state');
const invalid=structuredClone(heldSave);invalid.inv.push(invalid.management.carried);
assert.throws(()=>C.restoreHero(invalid),/Duplicate/);checks++;
await cmd({type:'tidy'});const tidied=JSON.stringify(p.inv);await cmd({type:'tidy'});ok(JSON.stringify(p.inv)===tidied,'tidy is deterministic');
await cmd({type:'bind',slot:0,skill:null});ok(p.quickSlots[0]===null,'shared skill picker can clear a quick slot');
const take=p.inv.items[0];await cmd({type:'carry',itemId:take._coopId});p.dead=true;await cmd({type:'returnManagement'});
ok(!p.management.carried,'held items can be returned after death');p.dead=false;
const remote=G.coop.makeHero('Other','vanguard');remote._coopId='other';s.players.push(remote);
await assert.rejects(()=>Cmd.execute(remote,{type:'carry',itemId:take._coopId}),/no longer/);checks++;
console.log(`PASS ${checks} shared inventory ownership, placement, crafting and persistence checks`);
