// Fresh context: no player save or personal filter is read or written.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const runtime=path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules');
const {chromium}=require(require.resolve('playwright',{paths:[runtime,__dirname]}));
const dest='tests/qa/loot_filter';fs.mkdirSync(dest,{recursive:true});
(async()=>{
  const browser=await chromium.launch({channel:'chrome',headless:true});
  const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];
  page.on('pageerror',e=>errors.push(String(e)));let checks=0;const ok=(v,m)=>{assert.ok(v,m);checks++;};
  try {
    await page.goto((process.env.GAME_REVIEW_URL||'http://127.0.0.1:8766')+'/index.html');
    await page.waitForSelector('#titleMenu button',{timeout:90000});
    await page.evaluate(async()=>{Sfx.setVol('master',0);await Game.newGame('Loot Filter Review','vanguard',false);await (await import('/tests/completed_hero_fixture.mjs')).loadCompletedHero(Game);Game.debugFlags.god=true;Game.state.monsters=[];UI.closeAll();UI.openEsc();});
    await page.getByRole('button',{name:'Loot Filter',exact:true}).click();
    const app=page.getByRole('dialog',{name:'Loot filter',exact:true});
    ok(await app.isVisible(),'pause menu integration');
    ok(await page.locator('.lf-rule').count()===4,'standard rule summaries');
    ok(await page.locator('.lf-preview-stats').innerText().then(t=>t.includes('7 shown')&&t.includes('1 hidden')),'standard sample evaluation');
    await page.screenshot({path:dest+'/desktop.png'});
    const builtins=await page.evaluate(()=>JSON.stringify(LootFilter.PRESETS));
    await page.getByLabel('Rule name',{exact:true}).fill('My rare items');
    await page.getByLabel('Rule name',{exact:true}).press('Tab');
    ok(await page.evaluate(()=>LootFilter.config.preset==='custom'&&LootFilter.rules()[0].name==='My rare items'),'first preset edit applies');
    ok(await page.evaluate(()=>JSON.stringify(LootFilter.PRESETS))===builtins,'presets immutable');
    await page.getByRole('button',{name:'Undo',exact:true}).click();
    ok(await page.evaluate(()=>LootFilter.config.preset==='standard'),'undo restores preset');
    await page.getByLabel('Condition 1 value',{exact:true}).selectOption('4');
    ok(await page.evaluate(()=>LootFilter.rules()[0].conditions[0].value===4),'rarity uses numeric value');
    await page.getByRole('button',{name:'↑ Move up'}).isDisabled().then(v=>ok(v,'first rule cannot move up'));
    await page.getByRole('button',{name:'↓ Move down'}).click();
    ok(await page.evaluate(()=>LootFilter.rules()[1].conditions[0].value===4),'reorder follows selected rule');
    await page.getByRole('button',{name:'Duplicate',exact:true}).click();
    ok(await page.locator('.lf-rule').count()===5,'duplicate rule');
    await page.getByRole('button',{name:'Delete',exact:true}).click();
    ok(await page.locator('.lf-rule').count()===4,'delete rule');
    await page.locator('[data-preset=endgame]').click();
    ok(await page.locator('.lf-preview-stats').innerText().then(t=>t.includes('5 shown')&&t.includes('3 hidden')),'endgame evaluation');
    await page.getByLabel('Reveal hidden samples').check();
    ok(await page.locator('[data-sample="Iron Sword"] .lf-drop').innerText()==='Iron Sword','reveal hidden preview');
    await page.getByRole('switch',{name:'Enable loot filter'}).click();
    ok(await page.locator('.lf-preview-stats').innerText().then(t=>t.includes('8 shown')),'disabled filter reveals all');
    await page.getByRole('switch',{name:'Enable loot filter'}).click();
    await page.getByRole('button',{name:'Restore custom'}).click();
    ok(await page.evaluate(()=>LootFilter.config.preset==='custom'&&LootFilter.rules()[1].conditions[0].value===4),'saved custom survives preset switching');
    await page.getByRole('button',{name:'Change reveal hidden key'}).click();await page.keyboard.press('z');
    ok(await page.evaluate(()=>LootFilter.config.revealKey==='z'),'rebind key');
    await page.getByRole('button',{name:'Change reveal hidden key'}).click();await page.keyboard.press('Escape');
    ok(await app.isVisible()&&await page.evaluate(()=>LootFilter.config.revealKey==='z'),'Escape cancels key capture');
    await page.getByRole('button',{name:'Import / export'}).click();
    const exported=await page.getByLabel('Filter JSON').inputValue();
    await page.getByLabel('Filter JSON').fill('{"preset":"custom","rules":[null]}');
    await page.getByRole('button',{name:'Import filter',exact:true}).click();
    ok(await page.getByRole('alert').isVisible(),'inline import validation');
    ok(await page.evaluate(()=>LootFilter.exportJSON())===exported,'invalid import is atomic');
    await page.getByLabel('Filter JSON').fill(exported);await page.getByRole('button',{name:'Import filter',exact:true}).click();
    ok(await page.locator('.lf-transfer').count()===0,'valid import closes sharing');
    await page.getByRole('button',{name:'Reset',exact:true}).click();
    ok(await page.evaluate(()=>LootFilter.config.preset==='standard'),'reset');
    await page.getByRole('button',{name:'Undo',exact:true}).click();
    ok(await page.evaluate(()=>LootFilter.config.preset==='custom'),'reset undo');
    await page.locator('[data-preset=showall]').click();
    ok(await page.locator('.lf-rule').count()===0,'empty preset is explained');
    await page.getByRole('button',{name:'+ Add rule',exact:true}).click();
    await page.getByLabel('Rule name',{exact:true}).fill('Test every drop');
    await page.getByRole('button',{name:'Remove condition 1',exact:true}).click();
    ok(await page.evaluate(()=>LootFilter.rules()[0].name==='Test every drop'&&LootFilter.rules()[0].conditions.length===0),'rename does not swallow next button click');
    await page.getByRole('button',{name:'Hide item',exact:true}).click();
    ok(await page.locator('.lf-preview-stats').innerText().then(t=>t.includes('3 shown')&&t.includes('5 hidden')),'catch-all keeps protected samples visible');
    await page.getByRole('button',{name:'Show item',exact:true}).click();
    await page.getByLabel('Label color mode',{exact:true}).selectOption('custom');
    await page.getByLabel('Label color',{exact:true}).fill('#12abef');
    await page.getByLabel('Light beam mode',{exact:true}).selectOption('custom');
    await page.getByLabel('Minimap dot mode',{exact:true}).selectOption('off');
    await page.getByLabel('Drop sound',{exact:true}).selectOption('none');
    await page.getByLabel('Label size (0.8–1.8×)',{exact:true}).fill('1.5');
    await page.getByLabel('Label size (0.8–1.8×)',{exact:true}).press('Tab');
    ok(await page.evaluate(()=>{const d=LootFilter.evaluate({gold:5});return d.color==='#12abef'&&d.beam==='#e8c681'&&d.minimap===null&&d.sound===null&&d.size===1.5;}),'appearance and silence reach actual evaluator');
    await page.getByRole('button',{name:'+ Add condition',exact:true}).click();
    await page.getByLabel('Condition 1 property',{exact:true}).selectOption('reqLvl');
    await page.getByLabel('Condition 1 value',{exact:true}).fill('not a number');
    await page.getByLabel('Condition 1 value',{exact:true}).press('Tab');
    ok(await page.evaluate(()=>LootFilter.rules()[0].conditions[0].value===0),'invalid numeric input cannot corrupt saved rule');
    await page.getByLabel('Condition 1 value',{exact:true}).fill('player-5');
    await page.getByLabel('Condition 1 value',{exact:true}).press('Tab');
    ok(await page.evaluate(()=>LootFilter.rules()[0].conditions[0].value==='player-5'),'player-relative input accepted');
    await page.getByLabel('Condition 1 property',{exact:true}).selectOption('quest');
    await page.getByLabel('Condition 1 value',{exact:true}).selectOption('false');
    ok(await page.evaluate(()=>LootFilter.rules()[0].conditions[0].value===false),'boolean conditions use actual false');
    await page.getByLabel('Condition 1 property',{exact:true}).selectOption('hasMod');
    await page.getByLabel('Minimum affix value',{exact:true}).fill('5');
    await page.getByLabel('Minimum affix value',{exact:true}).press('Tab');
    ok(await page.evaluate(()=>LootFilter.rules()[0].conditions[0].min===5),'affix threshold supported');
    await page.getByRole('button',{name:'Reset',exact:true}).click();
    for(const [width,height] of [[1920,1080],[1024,768],[640,900],[390,844]]) {
      await page.setViewportSize({width,height});
      await page.locator('.lf-body').evaluate(n=>n.scrollTop=0);
      ok(await app.evaluate(n=>{const r=n.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight&&n.scrollWidth<=n.clientWidth;}),'dialog fits '+width);
      ok(await page.locator('.lf-body').evaluate(n=>n.scrollWidth<=n.clientWidth),'content has no horizontal overflow '+width);
      await page.screenshot({path:dest+'/responsive-'+width+'.png'});
      if(width===390){await page.getByRole('button',{name:'Show item',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:dest+'/editor-mobile.png'});}
    }
    await page.getByRole('button',{name:'Done',exact:true}).focus();await page.keyboard.press('Tab');
    ok(await page.evaluate(()=>document.activeElement.getAttribute('role')==='switch'),'focus wraps within dialog');
    await page.keyboard.press('Escape');ok(await page.getByRole('button',{name:'Resume',exact:true}).isVisible(),'Escape returns to pause menu');
    await page.getByRole('button',{name:'Loot Filter',exact:true}).click();
    await page.getByRole('button',{name:'Done',exact:true}).click();ok(await page.locator('#escmenu').evaluate(n=>n.classList.contains('hidden')),'Done resumes');
    const saved=await page.evaluate(()=>LootFilter.exportJSON());await page.reload();await page.waitForSelector('#titleMenu button',{timeout:90000});
    ok(await page.evaluate(()=>LootFilter.exportJSON())===saved,'filter persists after reload');
    ok(!errors.length,'no runtime errors: '+errors.join('; '));
    fs.writeFileSync(dest+'/browser.json',JSON.stringify({status:'PASS',checks,errors},null,2)+'\n');console.log(JSON.stringify({status:'PASS',checks,errors}));
  } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
