"""Create the explicit audio assignments from the reviewed skill identity list.

The shipped catalog is standalone: audio never reads or depends on SkillVFX.
"""
from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parents[1]
rows = re.search(r'const assignments=`(.*?)`;', (ROOT/'js/skill_vfx.js').read_text(), re.S)[1].strip().splitlines()
families = {
 'steel': ['cloth', 'blade', 'steel', 'cloth', None],
 'fire': ['cloth', 'ember', 'fire', 'ember', 'fire'],
 'frost': ['cloth', 'ice', 'frost', 'ice', 'wind'],
 'storm': ['cloth', 'spark', 'spark', 'wind', 'wind'],
 'bone': ['bone', 'bone', 'bone', 'bone', None],
 'hex': ['shadow', 'hex', 'hex', 'breath', 'hex'],
 'poison': ['cloth', 'rot', 'rot', 'rot', 'wind'],
 'shadow': ['cloth', 'shadow', 'blood', 'shadow', 'wind'],
 'earth': ['roots', 'stone', 'stone', 'stone', 'wind'],
 'blood': ['cloth', 'blade', 'blood', 'breath', None],
 'nature': ['roots', 'growl', 'blood', 'roots', None],
 'bow': ['draw', 'bow', 'arrow', 'cloth', 'draw'],
 'trap': ['latch', 'latch', 'steel', 'latch', None],
 'warcry': ['breath', 'howl', 'shield', 'breath', None],
 'banner': ['cloth', 'chain', 'shield', 'cloth', None],
 'shield': ['cloth', 'shield', 'shield', 'chain', None],
 'chain': ['chain', 'chain', 'steel', 'chain', None],
}
special = {
 'arrow':'bow', 'volley':'bow', 'draw':'bow', 'ricochet':'bow', 'skewer':'bow', 'rain':'bow',
 'shout':'warcry', 'fear':'warcry', 'roar':'warcry', 'howl':'warcry', 'muster':'warcry',
 'banner':'banner', 'standard':'banner', 'parry':'shield', 'bulwark':'shield', 'bash':'shield',
 'grapple':'chain', 'barbed':'trap', 'tripwire':'trap', 'caltrop':'trap',
 'frosttrap':'frost', 'powder':'fire', 'claw':'fire', 'skeleton':'bone', 'mage':'poison',
 'fangform':'nature', 'bearform':'nature', 'stoneform':'earth', 'apexform':'fire',
 'wolf':'nature', 'boar':'earth', 'bear':'nature', 'hawk':'storm', 'devour':'bone',
 'packsacrifice':'blood', 'sacrifice':'fire', 'corpse':'poison', 'stance':'blood',
}
heavy = {'finish','execute','roar','fissure','leap','meteor','inferno','glacier','overload','golem','muster','sacrifice','corpse','outbreak','rain','powder','hemorrhage','bear','quake','tempest','stoneform','apexform'}
accents = {'finish':'shield','parry':'chain','execute':'blood','banner':'cloth','standard':'cloth','charge':'cloth','grapple':'latch','axe':'steel','fissure':'roots','bash':'chain','leap':'roots','meteor':'thunder','inferno':'thunder','glacier':'stone','overload':'thunder','golem':'stone','bonespear':'blade','muster':'bone','sacrifice':'blood','siphon':'breath','reap':'blade','corpse':'bone','outbreak':'breath','volley':'cloth','draw':'draw','ricochet':'steel','skewer':'blade','rain':'wind','barbed':'chain','tripwire':'latch','powder':'stone','decoy':'cloth','blink':'breath','smoke':'wind','afterimage':'blade','wolf':'roots','boar':'growl','hawk':'wind','bear':'roots','totem':'roots','cyclone':'wind','quake':'roots','tempest':'thunder','fangform':'roots','bearform':'roots','stoneform':'roots','apexform':'growl','claw':'blade'}
catalog = {}
audible_passives = {'emberwitch_0_2','emberwitch_1_2','gravebinder_0_3','gravebinder_1_4','gravebinder_1_6','kinship','primal_surge'}
for i, row in enumerate(rows):
    sid, material, motif = row.split()
    passive = motif.startswith('passive:')
    trigger = motif.split(':')[1] if passive and sid in audible_passives else None
    family = special.get(motif, 'steel' if material == 'gold' else material)
    catalog[sid] = dict(family=family, motif=motif, weight=1.25 if motif in heavy else .82 if passive else 1,
                        rate=round(.95+(i%7)*.015,3), accent=accents.get(motif), passive=passive, trigger=trigger)
catalog['basic'] = dict(family='steel', motif='slash', weight=.86, rate=1, accent=None, passive=False, trigger=None)
text = "/* Recorded skill audio identities; generated by tools/create_skill_audio_catalog.py. */\n'use strict';\nconst SkillAudioCatalog = (() => {\n"
text += '  const families = '+json.dumps(families, separators=(',', ':'))+';\n'
text += '  const recipes = '+json.dumps(catalog, indent=2)+';\n'
text += '  for(const row of Object.values(recipes))Object.freeze(row);\n  for(const row of Object.values(families))Object.freeze(row);\n  return Object.freeze({recipes:Object.freeze(recipes),families:Object.freeze(families)});\n})();\n'
(ROOT/'js/skill_audio_catalog.js').write_text(text, encoding='utf-8')
print('Wrote',len(catalog),'explicit sound assignments')
