"""Compile authored northern frames and exact compatible existing clips.

Original ImageGen files are never modified. Packing preserves native alpha,
registers whole silhouettes, and compiles the same masks used for picking.
"""
import argparse,hashlib,json
from pathlib import Path
from PIL import Image
from act1_sprite_cutouts import cutouts
from build_sprite_assets import actor_hit_shape

ROOT=Path(__file__).resolve().parents[1]
BASE=ROOT/'assets/act1_animations'
REPORT=BASE/'import.json'
def digest(path):return hashlib.sha256(path.read_bytes()).hexdigest()
def verify_sources(report):
    for key,source in report['sources'].items():
        if digest(ROOT/source['path'])!=source['sha256']:raise ValueError('Changed northern source '+key)
def manifest():return json.loads((ROOT/'js/sprite_manifest.js').read_text().split('DATA.SPRITE_MANIFEST = ',1)[1].strip().removesuffix(';'))
def install(entries,maps):
    if not REPORT.exists():return
    report=json.loads(REPORT.read_text())
    verify_sources(report)
    for key,e in report['entries'].items():
        if not (ROOT/e['src']).exists():raise ValueError('Missing northern atlas '+e['src'])
        entries[key]=e
    maps.setdefault('monsters',{}).update(report.get('monsterMaps',{}))

def pack(frames,art,target_height,seq):
    # Each sequence uses a single body scale, including collapsed remains.
    scale=target_height/frames[0].height
    roots=[]
    for f in frames:
        alpha=f.getchannel('A');strip=alpha.crop((0,max(0,f.height-max(4,f.height//12)),f.width,f.height))
        weights=[sum(strip.getpixel((x,y)) for y in range(strip.height)) for x in range(strip.width)]
        roots.append(sum(x*v for x,v in enumerate(weights))/max(1,sum(weights)))
    cw=max(192,32*int((2*max(max(x,f.width-x) for x,f in zip(roots,frames))*scale+32+31)//32))
    ch=max(192,32*int((max(f.height for f in frames)*scale+32+31)//32))
    anchor=[cw//2,ch-20];cells=[]
    for frame,x in zip(frames,roots):
        body=frame.resize((max(1,round(frame.width*scale)),max(1,round(frame.height*scale))),Image.Resampling.LANCZOS)
        cell=Image.new('RGBA',(cw,ch));cell.alpha_composite(body,(anchor[0]-round(x*scale),anchor[1]-body.height));cells.append(cell)
    atlas=Image.new('RGBA',(cw*6,ch*len(seq)))
    for i,cell in enumerate(cells):atlas.alpha_composite(cell,(i%6*cw,i//6*ch))
    path=BASE/'packed'/(art+'.webp');path.parent.mkdir(exist_ok=True);atlas.save(path,'WEBP',lossless=True,method=6)
    entry={'kind':'atlas','src':path.relative_to(ROOT).as_posix(),'revision':digest(path)[:12],
      'cell':[cw,ch],'cols':6,'rows':len(seq),'anchor':anchor,'anchors':[anchor]*len(cells),
      'bundle':'actors:act1','act1Art':True,'sequences':seq,'isolateFrameSampling':True,'hitShapes':[actor_hit_shape(f) for f in cells]}
    # Deliberately high-contrast review background makes alpha failures visible.
    review=Image.new('RGBA',atlas.size,'#24383e');review.alpha_composite(atlas)
    dest=ROOT/'tests/qa/act1_animation/atlases';dest.mkdir(parents=True,exist_ok=True);review.convert('RGB').save(dest/(art+'.webp'),quality=93)
    return entry,cells

def compile_catalog(cat,report,m):
    groups={g['id']:g for g in cat['groups']};runtime={}
    for id,s in cat['roster'].items():
        clips={};g=groups[s['art']]
        for kind in s['sequences']:
            owned=next(((key,e) for key,e in reversed(list(report['entries'].items())) if (e.get('art')==g['id'] or key=='actor.act1.'+g['id']) and kind in e.get('sequences',[])),None)
            if owned:clip={'asset':owned[0],'row':owned[1]['sequences'].index(kind)}
            elif kind in g['clips']:
                old=g['clips'][kind];key='actor.act1.reuse.'+old['asset'].removeprefix('actor.')
                report['entries'][key]={**m['entries'][old['asset']],'bundle':'actors:act1','act1Art':True}
                clip={'asset':key,'row':old['row']}
            else:continue
            if g['id']=='beacon':clip['scale']=1
            clips[kind]=clip
        # Between actions, stay on the same authored identity and anchor.
        # The Yeti has an explicit idle row; other sheets start their basic
        # action in a neutral ready pose. Never fall back to the old portrait.
        rests={}
        for suffix in (['','_1'] if id=='korvath' else ['']):
            basic=clips.get('cleave'+suffix) if id=='korvath' else clips.get(s['sequences'][0])
            if basic:
                entry=report['entries'][basic['asset']];idle='idle'+suffix
                rests['idle'+suffix]={**basic,'row':entry['sequences'].index(idle) if idle in entry.get('sequences',[]) else basic['row'],'frame':0}
        runtime[id]={**s,'clips':clips,'rests':rests}
    (ROOT/'js/act1_animation_catalog.js').write_text('/* Generated by tools/import_act1_animations.py. */\nDATA.ACT1_ANIMATIONS = '+json.dumps(runtime,separators=(',',':'))+';\n')
    return runtime

def main():
    p=argparse.ArgumentParser();p.add_argument('--only',nargs='+');p.add_argument('--check',action='store_true');args=p.parse_args()
    cat=json.loads((BASE/'catalog.json').read_text());m=manifest();report=json.loads(REPORT.read_text()) if REPORT.exists() else {'version':1,'entries':{},'sources':{},'monsterMaps':{}}
    if args.check:
        verify_sources(report)
        for key,e in report['entries'].items():
            assert m['entries'][key]==e,key
            im=Image.open(ROOT/e['src']);assert im.mode=='RGBA' and im.getchannel('A').getextrema()[0]==0,key
            if key.startswith('actor.act1.') and not key.startswith('actor.act1.reuse.'):
                w,h=e['cell']
                for row in range(e['rows']):
                    hashes=[]
                    for c in range(6):
                        f=im.crop((c*w,row*h,(c+1)*w,(row+1)*h));b=f.getbbox();assert b and b[0]>0 and b[1]>0 and b[2]<w and b[3]<h,(key,row,c,b)
                        assert actor_hit_shape(f)==e['hitShapes'][row*6+c],(key,'mask');hashes.append(hashlib.sha256(f.tobytes()).hexdigest())
                    assert len(set(hashes))==6,(key,row,'duplicate frame')
        runtime=compile_catalog(cat,report,m)
        for id,s in runtime.items():
            assert set(s['sequences'])==set(s['clips']),(id,'missing',set(s['sequences'])-set(s['clips']))
            assert 'idle' in s['rests'] and (id!='korvath' or 'idle_1' in s['rests']),(id,'missing ready pose')
        print('PASS',len(runtime),'enemies;',len(report['entries']),'atlases: complete clips, alpha, padding, masks, six unique frames');return
    jobs=json.loads((BASE/'jobs.json').read_text())
    # The yeti has a separate idle/movement row, used for its new base identity.
    jobs=[{'id':'yeti','rows':5,'groups':[{'id':'identity_frostmaw_yeti','rowOffset':0,'sequences':['idle','melee','breath','slam','death'],'reference':None}]}]+jobs
    groups={g['id']:g for g in cat['groups']}
    for job in jobs:
        if args.only and job['id'] not in args.only:continue
        source=BASE/'source'/('identity_frostmaw_yeti.png' if job['id']=='yeti' else job['id']+'.png')
        if not source.exists():continue
        im=Image.open(source)
        if im.mode!='RGBA' or im.getchannel('A').getextrema()[0]!=0:raise ValueError('Source lacks actual alpha: '+str(source))
        print('Packing',job['id'],flush=True);frames=cutouts(im,job['rows'],True)
        for g in job['groups']:
            seq=g['sequences'];own=frames[g['rowOffset']*6:(g['rowOffset']+len(seq))*6]
            if g['id']=='identity_frostmaw_yeti':target=148
            elif g['id']=='ironlord':
                e=m['entries'][m['maps']['bosses']['korvath']];w,h=e['cell'];ref=Image.open(ROOT/g['reference']).crop((0,0,w,h));b=ref.getbbox();target=b[3]-b[1]
            else:
                ref=Image.open(ROOT/g['reference']);b=ref.getbbox();target=b[3]-b[1]
            asset=g.get('assetId',g['id']);entry,cells=pack(own,asset,target,seq);entry['art']=g['id'];report['entries']['actor.act1.'+asset]=entry
            if g['id']=='identity_frostmaw_yeti':
                # Static walking presentation reads the same authored idle cell.
                frame=cells[0];box=frame.getbbox();base=frame.crop(box);path=BASE/'packed/identity_frostmaw_yeti_idle.webp';base.save(path,'WEBP',lossless=True)
                old=m['entries'][m['maps']['monsters']['identity_frost_wyrm']]
                key='actor.monster.identity_frostmaw_yeti';report['entries'][key]={**old,'src':path.relative_to(ROOT).as_posix(),'cell':list(base.size),'cols':1,'rows':1,'anchor':[base.width//2,base.height],
                    'bundle':'actors:act1','revision':digest(path)[:12],'hitShapes':[actor_hit_shape(base)]}
                report['monsterMaps']['identity_frostmaw_yeti']=key
        report['sources'][job['id']]={'path':source.relative_to(ROOT).as_posix(),'sha256':digest(source)}
    runtime=compile_catalog(cat,report,m);REPORT.write_text(json.dumps(report,indent=2)+'\n')
    install(m['entries'],m['maps']);(ROOT/'js/sprite_manifest.js').write_text('/* Generated by tools/build_sprite_assets.py. Do not hand-edit. */\n"use strict";\n\nDATA.SPRITE_MANIFEST = '+json.dumps(m,indent=2,sort_keys=True)+';\n')
    print('Compiled',sum(len(s['clips']) for s in runtime.values()),'of',sum(len(s['sequences']) for s in runtime.values()),'required enemy clips')

if __name__=='__main__':main()
